require_relative "./villagetopia/version"
require_relative "./app/cli"
require_relative "./app/user"
require_relative "./app/school"
require_relative "./data/school_scrapers/gifted_program"
require_relative "./data/school_scrapers/twice_exceptional_program"
require_relative "./app/your_villagetopia"
